# Generated by Django 5.2.16 on 2026-07-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('facilitator', 'Facilitator'), ('mentor', 'Mentor'), ('both', 'Facilitator & Mentor')], default='mentor', max_length=20)),
                ('title_company', models.CharField(blank=True, max_length=160, verbose_name='Role & company')),
                ('expertise', models.CharField(blank=True, max_length=200, verbose_name='Areas of expertise')),
                ('photo', models.ImageField(blank=True, upload_to='faculty/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Faculty members',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('event', models.CharField(blank=True, help_text="e.g. 'Cohort 4 Pitch Day'", max_length=160)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ImpactStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. 'Entrepreneurs Empowered'", max_length=80)),
                ('value', models.PositiveIntegerField(help_text='The number itself, e.g. 250')),
                ('suffix', models.CharField(blank=True, help_text="Optional, e.g. '+'", max_length=8)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='resources/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SpotlightVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtube_url', models.URLField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('photo', models.ImageField(blank=True, upload_to='team/')),
                ('bio', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('text', 'Picture & text'), ('video', 'Video (YouTube)')], default='text', max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('business', models.CharField(blank=True, help_text="Venture / country, e.g. 'AgroLink, Ghana'", max_length=160)),
                ('quote', models.TextField(blank=True, help_text='For text testimonials')),
                ('photo', models.ImageField(blank=True, upload_to='alumni/')),
                ('youtube_url', models.URLField(blank=True, help_text='For video testimonials: full YouTube link')),
                ('featured', models.BooleanField(default=False, help_text='Show on the home page')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
