# Generated by Django 5.2.16 on 2026-07-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text="e.g. '2024' or 'Cohort 1'", max_length=12)),
                ('text', models.CharField(help_text="Short line, e.g. 'Embark Academy launches'", max_length=140)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
