# Generated by Django 5.2.16 on 2026-07-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_milestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='Exact URL path, e.g. /about/', max_length=120, unique=True)),
                ('title', models.CharField(blank=True, max_length=70, verbose_name='SEO title')),
                ('description', models.CharField(blank=True, max_length=160, verbose_name='Meta description')),
            ],
            options={
                'verbose_name': 'Page SEO setting',
                'verbose_name_plural': 'Page SEO settings',
            },
        ),
    ]
