# Generated by Django 5.2.16 on 2026-07-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pagemeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='cohort',
            field=models.CharField(blank=True, help_text="e.g. 'Cohort 2, 2025'", max_length=60),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='link',
            field=models.URLField(blank=True, help_text='Their website or social page — linked from the spotlight page'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='link_label',
            field=models.CharField(blank=True, help_text="What to call that link, e.g. 'Instagram' or 'agrolink.co'. Defaults to the domain.", max_length=60),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='media_consent',
            field=models.BooleanField(default=False, help_text='Tick only once this alumnus has agreed their photo and video may be used. Entries without it are hidden from the public site.', verbose_name='Media release consent on file'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='on_spotlight',
            field=models.BooleanField(default=True, help_text='Untick to keep an entry out of the spotlight page.', verbose_name='Show on the Alumni Spotlight page'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='orientation',
            field=models.CharField(choices=[('auto', 'Detect automatically (Shorts are treated as vertical)'), ('landscape', 'Landscape — 16:9'), ('portrait', 'Vertical — 9:16')], default='auto', help_text='Only change this if a vertical clip was uploaded as a normal video.', max_length=10),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='story',
            field=models.TextField(blank=True, help_text='The write-up for the alumni spotlight page: what they build and the impact it has had. A few short paragraphs; blank lines start a new one.'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Paste any YouTube link — watch page, youtu.be, or a Short'),
        ),
    ]
