# Generated by Django 5.2.16 on 2026-07-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alumni_spotlight_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
