# Generated by Django 5.2.16 on 2026-09-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_promo_popup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Cohort 5', help_text='What this cycle is called on the site, e.g. “Cohort 5”.', max_length=40)),
                ('applications_open', models.DateField(help_text='First day people can apply.')),
                ('applications_close', models.DateField(help_text='Last day people can apply. The staff dashboard counts down to this.')),
                ('notify_from', models.DateField(verbose_name='Notifications from')),
                ('notify_to', models.DateField(verbose_name='Notifications until')),
                ('is_current', models.BooleanField(default=True, help_text='Only one cohort is used at a time. Ticking this one is enough — the most recent ticked cohort wins.', verbose_name='This is the cohort we are advertising')),
            ],
            options={
                'ordering': ['-applications_open'],
            },
        ),
    ]
