# Generated by Django 5.2.16 on 2026-09-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cohort'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What you will recognise this by in the dropdown, e.g. “Cohort 5 offer”. Never shown to the applicant.', max_length=80)),
                ('purpose', models.CharField(choices=[('approved', 'After approving someone'), ('declined', 'After declining someone'), ('any', 'Anything else')], default='approved', help_text='Which decision this is the usual reply to. It only decides which template is offered first.', max_length=10)),
                ('subject', models.CharField(help_text="The email's subject line. Placeholders work here too.", max_length=200)),
                ('body', models.TextField(help_text="The message. Use the placeholders listed beside the box to drop in the applicant's own details.")),
                ('is_default', models.BooleanField(default=False, help_text='The template pre-filled for its purpose. If several are ticked, the most recently edited wins.', verbose_name='Offer this one first')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email template',
                'verbose_name_plural': 'Email templates',
                'ordering': ['purpose', 'name'],
            },
        ),
    ]
