"""Country names and international dialling codes for the public forms.

One table, two derived choice lists. African countries are grouped first in
both, since that is where nearly every applicant, mentor, and volunteer is.

The stored value is the country *name*, not the ISO code: form submissions
are read by humans in the admin and in notification emails, and applications
predating these dropdowns already hold free-typed names. For the same reason
the choices live on the form, never on the model — a legacy row holding
"Nigeria " or "Cote d'Ivoire" must stay valid.
"""

# (iso2, name, dialling code). ISO 3166-1 alpha-2 is here as a stable key for
# future use (flags, geo lookups); nothing stores it yet.
AFRICA = [
    ("DZ", "Algeria", "+213"),
    ("AO", "Angola", "+244"),
    ("BJ", "Benin", "+229"),
    ("BW", "Botswana", "+267"),
    ("BF", "Burkina Faso", "+226"),
    ("BI", "Burundi", "+257"),
    ("CV", "Cabo Verde", "+238"),
    ("CM", "Cameroon", "+237"),
    ("CF", "Central African Republic", "+236"),
    ("TD", "Chad", "+235"),
    ("KM", "Comoros", "+269"),
    ("CD", "Congo (Democratic Republic of the)", "+243"),
    ("CG", "Congo (Republic of the)", "+242"),
    ("CI", "Côte d'Ivoire", "+225"),
    ("DJ", "Djibouti", "+253"),
    ("EG", "Egypt", "+20"),
    ("GQ", "Equatorial Guinea", "+240"),
    ("ER", "Eritrea", "+291"),
    ("SZ", "Eswatini", "+268"),
    ("ET", "Ethiopia", "+251"),
    ("GA", "Gabon", "+241"),
    ("GM", "Gambia", "+220"),
    ("GH", "Ghana", "+233"),
    ("GN", "Guinea", "+224"),
    ("GW", "Guinea-Bissau", "+245"),
    ("KE", "Kenya", "+254"),
    ("LS", "Lesotho", "+266"),
    ("LR", "Liberia", "+231"),
    ("LY", "Libya", "+218"),
    ("MG", "Madagascar", "+261"),
    ("MW", "Malawi", "+265"),
    ("ML", "Mali", "+223"),
    ("MR", "Mauritania", "+222"),
    ("MU", "Mauritius", "+230"),
    ("MA", "Morocco", "+212"),
    ("MZ", "Mozambique", "+258"),
    ("NA", "Namibia", "+264"),
    ("NE", "Niger", "+227"),
    ("NG", "Nigeria", "+234"),
    ("RW", "Rwanda", "+250"),
    ("ST", "São Tomé and Príncipe", "+239"),
    ("SN", "Senegal", "+221"),
    ("SC", "Seychelles", "+248"),
    ("SL", "Sierra Leone", "+232"),
    ("SO", "Somalia", "+252"),
    ("ZA", "South Africa", "+27"),
    ("SS", "South Sudan", "+211"),
    ("SD", "Sudan", "+249"),
    ("TZ", "Tanzania", "+255"),
    ("TG", "Togo", "+228"),
    ("TN", "Tunisia", "+216"),
    ("UG", "Uganda", "+256"),
    ("EH", "Western Sahara", "+212"),
    ("ZM", "Zambia", "+260"),
    ("ZW", "Zimbabwe", "+263"),
]

REST_OF_WORLD = [
    ("AF", "Afghanistan", "+93"),
    ("AL", "Albania", "+355"),
    ("AD", "Andorra", "+376"),
    ("AG", "Antigua and Barbuda", "+1268"),
    ("AR", "Argentina", "+54"),
    ("AM", "Armenia", "+374"),
    ("AU", "Australia", "+61"),
    ("AT", "Austria", "+43"),
    ("AZ", "Azerbaijan", "+994"),
    ("BS", "Bahamas", "+1242"),
    ("BH", "Bahrain", "+973"),
    ("BD", "Bangladesh", "+880"),
    ("BB", "Barbados", "+1246"),
    ("BY", "Belarus", "+375"),
    ("BE", "Belgium", "+32"),
    ("BZ", "Belize", "+501"),
    ("BT", "Bhutan", "+975"),
    ("BO", "Bolivia", "+591"),
    ("BA", "Bosnia and Herzegovina", "+387"),
    ("BR", "Brazil", "+55"),
    ("BN", "Brunei", "+673"),
    ("BG", "Bulgaria", "+359"),
    ("KH", "Cambodia", "+855"),
    ("CA", "Canada", "+1"),
    ("CL", "Chile", "+56"),
    ("CN", "China", "+86"),
    ("CO", "Colombia", "+57"),
    ("CR", "Costa Rica", "+506"),
    ("HR", "Croatia", "+385"),
    ("CU", "Cuba", "+53"),
    ("CY", "Cyprus", "+357"),
    ("CZ", "Czechia", "+420"),
    ("DK", "Denmark", "+45"),
    ("DM", "Dominica", "+1767"),
    ("DO", "Dominican Republic", "+1809"),
    ("EC", "Ecuador", "+593"),
    ("SV", "El Salvador", "+503"),
    ("EE", "Estonia", "+372"),
    ("FJ", "Fiji", "+679"),
    ("FI", "Finland", "+358"),
    ("FR", "France", "+33"),
    ("GE", "Georgia", "+995"),
    ("DE", "Germany", "+49"),
    ("GR", "Greece", "+30"),
    ("GD", "Grenada", "+1473"),
    ("GT", "Guatemala", "+502"),
    ("GY", "Guyana", "+592"),
    ("HT", "Haiti", "+509"),
    ("HN", "Honduras", "+504"),
    ("HK", "Hong Kong", "+852"),
    ("HU", "Hungary", "+36"),
    ("IS", "Iceland", "+354"),
    ("IN", "India", "+91"),
    ("ID", "Indonesia", "+62"),
    ("IR", "Iran", "+98"),
    ("IQ", "Iraq", "+964"),
    ("IE", "Ireland", "+353"),
    ("IL", "Israel", "+972"),
    ("IT", "Italy", "+39"),
    ("JM", "Jamaica", "+1876"),
    ("JP", "Japan", "+81"),
    ("JO", "Jordan", "+962"),
    ("KZ", "Kazakhstan", "+7"),
    ("KI", "Kiribati", "+686"),
    ("KW", "Kuwait", "+965"),
    ("KG", "Kyrgyzstan", "+996"),
    ("LA", "Laos", "+856"),
    ("LV", "Latvia", "+371"),
    ("LB", "Lebanon", "+961"),
    ("LI", "Liechtenstein", "+423"),
    ("LT", "Lithuania", "+370"),
    ("LU", "Luxembourg", "+352"),
    ("MO", "Macao", "+853"),
    ("MY", "Malaysia", "+60"),
    ("MV", "Maldives", "+960"),
    ("MT", "Malta", "+356"),
    ("MH", "Marshall Islands", "+692"),
    ("MX", "Mexico", "+52"),
    ("FM", "Micronesia", "+691"),
    ("MD", "Moldova", "+373"),
    ("MC", "Monaco", "+377"),
    ("MN", "Mongolia", "+976"),
    ("ME", "Montenegro", "+382"),
    ("MM", "Myanmar", "+95"),
    ("NR", "Nauru", "+674"),
    ("NP", "Nepal", "+977"),
    ("NL", "Netherlands", "+31"),
    ("NZ", "New Zealand", "+64"),
    ("NI", "Nicaragua", "+505"),
    ("KP", "North Korea", "+850"),
    ("MK", "North Macedonia", "+389"),
    ("NO", "Norway", "+47"),
    ("OM", "Oman", "+968"),
    ("PK", "Pakistan", "+92"),
    ("PW", "Palau", "+680"),
    ("PS", "Palestine", "+970"),
    ("PA", "Panama", "+507"),
    ("PG", "Papua New Guinea", "+675"),
    ("PY", "Paraguay", "+595"),
    ("PE", "Peru", "+51"),
    ("PH", "Philippines", "+63"),
    ("PL", "Poland", "+48"),
    ("PT", "Portugal", "+351"),
    ("PR", "Puerto Rico", "+1787"),
    ("QA", "Qatar", "+974"),
    ("RO", "Romania", "+40"),
    ("RU", "Russia", "+7"),
    ("KN", "Saint Kitts and Nevis", "+1869"),
    ("LC", "Saint Lucia", "+1758"),
    ("VC", "Saint Vincent and the Grenadines", "+1784"),
    ("WS", "Samoa", "+685"),
    ("SM", "San Marino", "+378"),
    ("SA", "Saudi Arabia", "+966"),
    ("RS", "Serbia", "+381"),
    ("SG", "Singapore", "+65"),
    ("SK", "Slovakia", "+421"),
    ("SI", "Slovenia", "+386"),
    ("SB", "Solomon Islands", "+677"),
    ("KR", "South Korea", "+82"),
    ("ES", "Spain", "+34"),
    ("LK", "Sri Lanka", "+94"),
    ("SR", "Suriname", "+597"),
    ("SE", "Sweden", "+46"),
    ("CH", "Switzerland", "+41"),
    ("SY", "Syria", "+963"),
    ("TW", "Taiwan", "+886"),
    ("TJ", "Tajikistan", "+992"),
    ("TH", "Thailand", "+66"),
    ("TL", "Timor-Leste", "+670"),
    ("TO", "Tonga", "+676"),
    ("TT", "Trinidad and Tobago", "+1868"),
    ("TR", "Türkiye", "+90"),
    ("TM", "Turkmenistan", "+993"),
    ("TV", "Tuvalu", "+688"),
    ("UA", "Ukraine", "+380"),
    ("AE", "United Arab Emirates", "+971"),
    ("GB", "United Kingdom", "+44"),
    ("US", "United States", "+1"),
    ("UY", "Uruguay", "+598"),
    ("UZ", "Uzbekistan", "+998"),
    ("VU", "Vanuatu", "+678"),
    ("VA", "Vatican City", "+379"),
    ("VE", "Venezuela", "+58"),
    ("VN", "Vietnam", "+84"),
    ("YE", "Yemen", "+967"),
]

ALL = AFRICA + REST_OF_WORLD

AFRICA_LABEL = "Africa"
ELSEWHERE_LABEL = "Rest of the world"


def country_choices():
    """Grouped <optgroup> choices whose value is the country name."""
    return [
        ("", "Select country…"),
        (AFRICA_LABEL, [(name, name) for _, name, _ in AFRICA]),
        (ELSEWHERE_LABEL, [(name, name) for _, name, _ in REST_OF_WORLD]),
    ]


def dial_code_choices():
    """Grouped dialling-code choices, e.g. ("+234", "Nigeria (+234)").

    Several countries share a code (+212 Morocco and Western Sahara, +7 Russia
    and Kazakhstan, +1 US and Canada), which is fine — the value stored is the
    code, and duplicate values in a <select> are legal. Each keeps its own
    label so the person choosing can find their country by name.
    """
    return [
        ("", "Code…"),
        (AFRICA_LABEL, [(dial, f"{name} ({dial})") for _, name, dial in AFRICA]),
        (ELSEWHERE_LABEL, [(dial, f"{name} ({dial})") for _, name, dial in REST_OF_WORLD]),
    ]


def valid_dial_codes():
    """The set of accepted codes — duplicates collapsed."""
    return {dial for _, _, dial in ALL}
