# Generated by Django 5.2.16 on 2026-07-19 18:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL part, auto-suggested from title', max_length=220, unique=True)),
                ('category', models.CharField(choices=[('youth-development', 'Youth Development'), ('ai-entrepreneurship', 'AI & Entrepreneurship')], default='youth-development', max_length=40)),
                ('cover_image', models.ImageField(blank=True, upload_to='blog/')),
                ('excerpt', models.TextField(help_text='Short summary shown on cards (max 300 chars)', max_length=300)),
                ('body', models.TextField(help_text="The article. Blank line = new paragraph. Lines starting with '## ' become subheadings.")),
                ('author_name', models.CharField(default='IADEBAYO Foundation', max_length=120)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('seo_title', models.CharField(blank=True, help_text='Optional. Overrides the browser/search title', max_length=70)),
                ('seo_description', models.CharField(blank=True, help_text='Optional. Meta description for search engines', max_length=160)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
