# Generated by Django 5.2.16 on 2026-07-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False, help_text='Tick once the team has handled this')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmbarkApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False, help_text='Tick once the team has handled this')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('applicant_status', models.CharField(choices=[('student', 'Undergraduate student'), ('graduate', 'Recent graduate')], max_length=20)),
                ('institution', models.CharField(max_length=160, verbose_name='University / institution')),
                ('business_name', models.CharField(max_length=160)),
                ('business_description', models.TextField(help_text='What the business does and its traction so far')),
                ('business_sector', models.CharField(max_length=120)),
                ('motivation', models.TextField(verbose_name='Why do you want to join Embark?')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacultyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False, help_text='Tick once the team has handled this')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('faculty_option', models.CharField(choices=[('facilitator', 'Facilitator'), ('mentor', 'Mentor'), ('both', 'Both')], max_length=20)),
                ('country', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('motivation', models.TextField(verbose_name='Your motivation')),
                ('about', models.TextField(verbose_name='Tell us a little about you')),
                ('linkedin', models.URLField(blank=True, verbose_name='Your LinkedIn')),
                ('instagram', models.CharField(blank=True, max_length=120, verbose_name='Your IG')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False, help_text='Tick once the team has handled this')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartnershipInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False, help_text='Tick once the team has handled this')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(max_length=160, verbose_name='Organization name')),
                ('website', models.URLField(blank=True)),
                ('country', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('proposal', models.TextField(verbose_name='How do you intend to partner with us?')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False, help_text='Tick once the team has handled this')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('skills', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('motivation', models.TextField(verbose_name='Your motivation')),
                ('about', models.TextField(verbose_name='About you')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('instagram', models.CharField(blank=True, max_length=120, verbose_name='IG')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
