# Generated by Django 5.2.16 on 2026-08-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_business_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarkapplication',
            name='entrepreneurship_view',
            field=models.TextField(blank=True, help_text='Explain briefly.', verbose_name='What do you think the goal of entrepreneurship is — impact or profit?'),
        ),
        migrations.AlterField(
            model_name='embarkapplication',
            name='business_sector',
            field=models.CharField(blank=True, choices=[('agriculture', 'Agriculture'), ('beauty', 'Beauty'), ('construction', 'Construction'), ('creative_arts', 'Creative Arts'), ('education', 'Education'), ('energy', 'Energy'), ('entertainment', 'Entertainment'), ('events', 'Events'), ('fashion', 'Fashion'), ('finance', 'Finance'), ('food', 'Food'), ('healthcare', 'Healthcare'), ('hospitality', 'Hospitality'), ('logistics', 'Logistics'), ('manufacturing', 'Manufacturing'), ('media', 'Media'), ('professional_services', 'Professional Services'), ('real_estate', 'Real Estate'), ('retail', 'Retail'), ('social_enterprise', 'Social Enterprise'), ('sports', 'Sports'), ('technology', 'Technology'), ('tourism', 'Tourism'), ('other', 'Other')], max_length=120, verbose_name='Which sector does your business operate in?'),
        ),
    ]
