# Generated by Django 5.2.16 on 2026-08-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_sector_and_entrepreneurship_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarkapplication',
            name='business_social_handle',
            field=models.CharField(blank=True, max_length=160, verbose_name='Business social media handle'),
        ),
        migrations.AddField(
            model_name='embarkapplication',
            name='business_website',
            field=models.URLField(blank=True, max_length=300, verbose_name='Business website'),
        ),
        migrations.AddField(
            model_name='embarkapplication',
            name='linkedin',
            field=models.URLField(blank=True, max_length=300, verbose_name='LinkedIn profile'),
        ),
        migrations.AddField(
            model_name='embarkapplication',
            name='social_handle_2',
            field=models.CharField(blank=True, max_length=160, verbose_name='Another personal handle'),
        ),
        migrations.AlterField(
            model_name='embarkapplication',
            name='business_video_url',
            field=models.URLField(blank=True, help_text="<strong>Your video should answer three things:</strong><ol class='form-help-brief'><li><b>Who you are</b> — your name, where you are, what you study or studied.</li><li><b>What your business does</b> — what you sell, to whom, and how it is going.</li><li><b>Why you should be chosen</b> — what Embark would change for your venture.</li></ol>About a minute is plenty, and filmed on a phone is perfectly fine — we are listening to what you say, not judging the production. <strong>How to share it:</strong> upload the clip to Google Drive, open it, choose Share, set it to “Anyone with the link”, then paste that link here. An unlisted YouTube, Vimeo or Dropbox link works too. A private link cannot be reviewed, and an application we cannot watch cannot be assessed.", max_length=500, verbose_name='Link to your one-minute video'),
        ),
        migrations.AlterField(
            model_name='embarkapplication',
            name='social_handle',
            field=models.CharField(blank=True, max_length=160, verbose_name='Personal social media handle'),
        ),
    ]
