# Generated by Django 5.2.16 on 2026-08-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_applicant_linkedin_and_business_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartialApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False, help_text='Tick once the team has handled this')),
                ('phone_code', models.CharField(blank=True, max_length=8, verbose_name='Country code')),
                ('draft_id', models.CharField(help_text="Random id the applicant's browser keeps beside their local draft.", max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Full name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email address')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Phone number')),
                ('country', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('institution', models.CharField(blank=True, max_length=160, verbose_name='Institution')),
                ('business_name', models.CharField(blank=True, max_length=160)),
                ('answers', models.JSONField(blank=True, default=dict, verbose_name='Everything typed so far')),
                ('furthest_step', models.PositiveSmallIntegerField(default=1, verbose_name='Furthest section reached')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Set when a full application arrives from this draft or this email address. Rows with a date here need no chasing.', null=True, verbose_name='Finished the application')),
            ],
            options={
                'verbose_name': 'Unfinished application',
                'verbose_name_plural': 'Unfinished applications',
                'ordering': ['-updated_at'],
            },
        ),
    ]
