# Generated by Django 5.2.16 on 2026-08-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_partialapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='embarkapplication',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='facultyapplication',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='partialapplication',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='partnershipinquiry',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
