# Generated by Django 5.2.16 on 2026-09-23 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_acknowledged_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='embarkapplication',
            name='decided_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='embarkapplication',
            name='decided_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Who recorded the decision.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='embarkapplication',
            name='decision',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('declined', 'Declined')], help_text='Blank until the team has decided.', max_length=10),
        ),
        migrations.AddField(
            model_name='embarkapplication',
            name='decision_email_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
