# Generated by Django 5.2.16 on 2026-09-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0010_embarkapplication_decided_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partialapplication',
            name='nudge_sent_at',
            field=models.DateTimeField(blank=True, editable=False, help_text="When the 'you were nearly there' email was accepted for delivery. Written only on a successful send, so a failure can be retried, and a second send is a deliberate choice rather than an accident.", null=True, verbose_name='Reminder sent'),
        ),
        migrations.AlterField(
            model_name='embarkapplication',
            name='entrepreneurship_view',
            field=models.TextField(blank=True, help_text='Explain briefly.', verbose_name='What do you think the goal of entrepreneurship is — impact or profit?'),
        ),
    ]
