# Generated by Django 5.2.16 on 2026-09-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0011_partialapplication_nudge_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embarkapplication',
            name='entrepreneurship_view',
            field=models.TextField(blank=True, help_text='Explain briefly.', verbose_name='What do you think the goal of entrepreneurship is - impact or profit?'),
        ),
    ]
