# Generated by Django 5.2.16 on 2026-09-24 12:44

import django.db.models.deletion
from django.db import migrations, models


def reserve_existing_emails(apps, schema_editor):
    application = apps.get_model("submissions", "EmbarkApplication")
    identity = apps.get_model("submissions", "ApplicationEmailIdentity")
    database = schema_editor.connection.alias
    # Keep every historical submission; reserve each email against its first row.
    for pk, email in application.objects.using(database).order_by("pk").values_list("pk", "email").iterator():
        email = (email or "").strip().lower()
        if email:
            identity.objects.using(database).get_or_create(email=email, defaults={"application_id": pk})


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0012_alter_embarkapplication_entrepreneurship_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationEmailIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='submissions.embarkapplication')),
            ],
        ),
        migrations.RunPython(reserve_existing_emails, migrations.RunPython.noop),
    ]
